"""
MAlmasabi/Indirect-Prompt-Injection-BIPIA-GPT -> Example schema mapping
(docs/DATA_SOURCES.md, D19).

CC BY-SA 4.0, gated. 70,000 rows, single "train" split, {context,
user_intent, label, source}. Confirmed by direct cross-tab (not assumed):
label==0 rows are *always* source=="Generated by GPT-4o-mini" (35,000) and
label==1 rows are *always* source=="BIPIA" (35,000) -- i.e. this dataset's
entire malicious half is pre-materialized from the same BIPIA benchmark
`src/data/sources/bipia.py` also pulls directly. Flagged here for the
eventual D13 composition decision: combining this source's malicious half
with our own bipia.py output risks double-counting overlapping BIPIA-derived
content, not two independent malicious pools.

Same known gap as prodnull.py: no attack-category column in this release,
so every malicious row defaults to InjectionTechnique.OTHER rather than a
guessed category.
"""

import json
from pathlib import Path
from typing import Iterator

from src.data.schema import ContentSourceType, Example, InjectionTechnique, Label

RAW_DIR = Path("data/raw/malmasabi")


def pull_raw(out_dir: Path = RAW_DIR) -> None:
    from datasets import load_dataset

    out_dir.mkdir(parents=True, exist_ok=True)
    ds = load_dataset("MAlmasabi/Indirect-Prompt-Injection-BIPIA-GPT")["train"]
    with open(out_dir / "train.jsonl", "w") as f:
        for row in ds:
            f.write(json.dumps(row) + "\n")


def map_row_to_example(row: dict, index: int) -> Example:
    is_malicious = row["label"] == 1
    return Example(
        example_id=f"malmasabi-{index}",
        content_source_type=ContentSourceType.TOOL_OUTPUT,
        candidate_content=[row["context"]],
        label=Label.MALICIOUS if is_malicious else Label.BENIGN,
        agent_task_context=row["user_intent"],
        technique=InjectionTechnique.OTHER if is_malicious else None,
        source="malmasabi",
        is_redteam=False,
        notes=f"provenance={row['source']}",
    )


def load_examples(raw_dir: Path = RAW_DIR) -> Iterator[Example]:
    path = raw_dir / "train.jsonl"
    with open(path) as f:
        for index, line in enumerate(f):
            yield map_row_to_example(json.loads(line), index=index)
